
import { useMemo } from "react";
import { Expense, Category, Budget } from "@/types/finance";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Lightbulb, TrendingDown, TrendingUp, AlertTriangle } from "lucide-react";

interface AIInsightsProps {
  expenses: Expense[];
  categories: Category[];
  budgets: Budget[];
}

// Mock AI insights - in a real app, this would be generated by Gemini AI
const AIInsights = ({ expenses, categories, budgets }: AIInsightsProps) => {
  const insights = useMemo(() => {
    if (!expenses.length) return [];

    const totalSpent = expenses.reduce((sum, exp) => sum + exp.amount, 0);
    
    const categoryTotals = expenses.reduce((acc, expense) => {
      const categoryId = expense.categoryId;
      if (!acc[categoryId]) acc[categoryId] = 0;
      acc[categoryId] += expense.amount;
      return acc;
    }, {} as Record<string, number>);

    const getBudget = (categoryId: string) => {
      return budgets.find(b => b.categoryId === categoryId)?.amount || 0;
    };

    const getCategoryName = (categoryId: string) => {
      return categories.find(c => c.id === categoryId)?.name || "Unknown";
    };

    const result = [];

    // Find highest spending category
    const highestCategory = Object.entries(categoryTotals)
      .sort((a, b) => b[1] - a[1])[0];
    
    if (highestCategory) {
      result.push({
        title: "Highest Expense Category",
        message: `Your highest spending is in ${getCategoryName(highestCategory[0])} at $${highestCategory[1].toFixed(2)}, which is ${((highestCategory[1] / totalSpent) * 100).toFixed(1)}% of your total expenses.`,
        icon: TrendingUp,
        color: "text-amber-500",
      });
    }

    // Check for budget overruns
    const overBudget = Object.entries(categoryTotals)
      .filter(([categoryId, spent]) => {
        const budget = getBudget(categoryId);
        return budget > 0 && spent > budget;
      })
      .map(([categoryId, spent]) => ({
        category: getCategoryName(categoryId),
        spent,
        budget: getBudget(categoryId),
        overage: spent - getBudget(categoryId),
      }))
      .sort((a, b) => b.overage - a.overage);

    if (overBudget.length > 0) {
      result.push({
        title: "Budget Alert",
        message: `You've exceeded your budget in ${overBudget[0].category} by $${overBudget[0].overage.toFixed(2)}. Consider reviewing your spending in this category.`,
        icon: AlertTriangle,
        color: "text-red-500",
      });
    }

    // Savings opportunities
    result.push({
      title: "Savings Opportunity",
      message: "Based on your spending patterns, you could save approximately 15% on food expenses by meal prepping on weekends.",
      icon: TrendingDown,
      color: "text-green-500",
    });

    // General advice
    result.push({
      title: "Personal Finance Tip",
      message: "Consider the 50/30/20 rule: 50% of income for needs, 30% for wants, and 20% for savings and debt repayment.",
      icon: Lightbulb,
      color: "text-blue-500",
    });

    return result;
  }, [expenses, categories, budgets]);

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle>AI-Powered Insights</CardTitle>
        </CardHeader>
        <CardContent>
          {insights.length > 0 ? (
            <div className="space-y-6">
              {insights.map((insight, index) => (
                <div key={index} className="flex border rounded-lg p-4 bg-white">
                  <div className={`${insight.color} mr-4 mt-1`}>
                    <insight.icon className="h-5 w-5" />
                  </div>
                  <div>
                    <h3 className="font-medium text-gray-900">{insight.title}</h3>
                    <p className="text-gray-600 mt-1">{insight.message}</p>
                  </div>
                </div>
              ))}
            </div>
          ) : (
            <div className="text-center py-8 text-gray-500">
              Add more expenses to generate AI insights
            </div>
          )}
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Ask AI Assistant</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="border rounded-lg p-4 bg-gray-50 text-center">
            <p className="text-gray-600 mb-4">
              In a real application, this section would allow users to ask questions about their finances and get AI-powered responses from Gemini API.
            </p>
            <div className="flex items-center border rounded-lg bg-white p-3">
              <input
                type="text"
                placeholder="Ask a question about your finances..."
                className="flex-1 border-0 focus:outline-none bg-transparent"
                disabled
              />
              <Button variant="ghost" className="ml-2" disabled>
                Ask AI
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

export default AIInsights;
